import org.apache.hadoop.fs.shell.PathExceptions.PathIOException;
public class FunctionUse2272 {
public void funcUse() {
PathIOException pathioexception = new PathIOException();
pathioexception.getMessage();
}
}